"""initial_fod_snapshots

Revision ID: 7ba80f0c59ff
Revises: 
Create Date: 2026-03-29 10:47:36.824150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba80f0c59ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fod_snapshots', 'confidence',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fod_snapshots', 'confidence',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
